event = input("What event was held? ")
event_type = input("What type of event was held? ")
yellow_house = int(input("How many points did Yellow House earn? "))
blue_house = int(input("How many points did Blue House earn? "))
green_house = int(input("How many points did Green House earn? "))
red_house = int(input("How many points did Red House earn? "))